export { default as HomeView } from './HomeView'
export { default as LoginView } from './LoginView'
export { default as RegisterView } from './RegisterView'
export { default as VerifyView } from './VerifyView'
export { default as OAuthIdentifyView } from './OAuthIdentifyView'
export { default as Verify2FAView } from './Verify2FAView'