export const MfaErrorCodes = {
  MFA_METHOD_INVALID: "MFA_METHOD_INVALID",
  MFA_ALREADY_CONFIGURED: "MFA_ALREADY_CONFIGURED",
  MFA_ENROLLMENT_NOT_FOUND: "MFA_ENROLLMENT_NOT_FOUND",
  MFA_CREDENTIALS_MISSING: "MFA_CREDENTIALS_MISSING",
  MFA_VERIFICATION_FAILED: "MFA_VERIFICATION_FAILED",
  MFA_INVALID_CODE: "MFA_INVALID_CODE",
  MFA_EXPIRED: "MFA_EXPIRED",
  MFA_QR_GENERATION_FAILED: "MFA_QR_GENERATION_FAILED",
  MFA_DECRYPTION_FAILED: "MFA_DECRYPTION_FAILED",
  MFA_ENROLLMENT_FETCH_FAILED: "MFA_ENROLLMENT_FETCH_FAILED",
} as const

export type MfaErrorCode = (typeof MfaErrorCodes)[keyof typeof MfaErrorCodes]
