export const OAuthErrorCodes = {
  OAUTH_FAILED_TO_AUTHENTICATE: "OAUTH_FAILED_TO_AUTHENTICATE",
  OAUTH_INVALID_STATE: "OAUTH_INVALID_STATE",
  OAUTH_AUTHORIZATION_CODE_MISSING: "OAUTH_AUTHORIZATION_CODE_MISSING",
  OAUTH_EMAIL_NOT_PROVIDED: "OAUTH_EMAIL_NOT_PROVIDED",
  OAUTH_PROVIDER_INVALID: "OAUTH_PROVIDER_INVALID",
  OAUTH_PROVIDER_UNSUPPORTED: "OAUTH_PROVIDER_UNSUPPORTED",
  OAUTH_USERINFO_FETCH_FAILED: "OAUTH_USERINFO_FETCH_FAILED",
  OAUTH_DISCONNECT_NOT_POSSIBLE: "OAUTH_DISCONNECT_NOT_POSSIBLE",
  OAUTH_NOT_FOUND: "OAUTH_NOT_FOUND",
} as const

export type OAuthErrorCode =
  (typeof OAuthErrorCodes)[keyof typeof OAuthErrorCodes]
