export enum DomainErrorType {
  INVALID_OPERATION,
  VALIDATION,
  ACCESS_DENIED,
  ACCESS_FORBIDDEN,
  RESOURCE_MISSING,
  OPERATION_TIMEOUT,
  CONFLICT,
  UNPROCESSABLE_CONTENT,
  RATE_LIMIT,
  UNEXPECTED,
}
